theme: jekyll-theme-Hacker
title: T3chnocr4t:~#
description: <p>
  <a href="https://github.com/DenverCoder1/readme-typing-svg"><img src="https://readme-typing-svg.herokuapp.com?&font=IBM+Plex+Sans&color=abcdef&size=20&lines=Welcome+to+my+GitHub+Profile!;I'm+a+Cyber+Security+Analysts;Aspiring+Penetration+Tester." /></a>
</p>
show_downloads: false
show_repo: false

safe: true

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
