theme: jekyll-theme-Hacker
title: T3chnocr4t:~#
description: Looking 🔭 For Something Hidden....

show_downloads: false
show_repo: false

safe: true

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

url: "https://t3chnocr4t.github.io/"
image: "/assets/images/default-preview.jpg"
