theme: jekyll-theme-Hacker
title: T3chnocr4t:~#
description: Looking 🔭 For Something Hidden....
image: /image/naruto.jpg

show_downloads: false
show_repo: false

safe: true

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap
